# .travis.yml
language: ruby
rvm:
  - 2.2.0
env:
  - TRAITDB_PG_TEST_USER=postgres TEST_SUITE=units
  - TRAITDB_PG_TEST_USER=postgres TEST_SUITE=functionals
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - "bundle exec rake test:$TEST_SUITE"
before_script:
  - psql -c 'create database traitdb_test' -U postgres
