development:
  access_key_id: <%= ENV['TRAITDB_S3_DEVELOPMENT_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['TRAITDB_S3_DEVELOPMENT_SECRET_ACCESS_KEY'] %>
test:
  access_key_id: <%= ENV['TRAITDB_S3_TEST_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['TRAITDB_S3_TEST_ACCESS_KEY_ID'] %>
production:
  access_key_id: <%= ENV['TRAITDB_S3_PRODUCTION_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['TRAITDB_S3_PRODUCTION_SECRET_ACCESS_KEY'] %>
