development:
  bucket: <%= ENV['TRAITDB_S3_BUCKET_NAME'] %>
  access_key_id: <%= ENV['TRAITDB_S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['TRAITDB_S3_SECRET_ACCESS_KEY'] %>
test: &development
production: &development
